spring.application.name=github-action
server.port=9908


spring.datasource.driver-class-name=oracle.jdbc.OracleDriver
#spring.datasource.url=jdbc:oracle:thin:@//localhost:1521/orcl
#spring.datasource.username=C##MYAPP
#spring.datasource.password=NewPass123


spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:oracle:thin:@//localhost:1521/orcl}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:C##MYAPP}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:NewPass123}

# JPA / Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
#spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.Oracle12cDialect
spring.jpa.properties.hibernate.format_sql=true